server:
  port: 8008

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: dkagh
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[show_sql]": true
        "[format_sql]": true
